### ISSUE TITLE
const: Not an editor command (use of new vim feature)

### ISSUE THREAD

**Issue by olof** [segeljakt/vim-isotope#2]
Hello, this is not a bug as much as a compatibility issue with older versions of vim; having it documented at least here on github may help some users.

My version of vim (`2:8.1.0875-5ubuntu2.1`) complains about const not being an editor command when I first tried using this plugin (errors triggered when I try to interact with the commands), with errors pointing to charset.vim.

```
Error detected while processing <repo path>/autoload/isotope/charset.vim:
...
E492: Not an editor command: const s:keys = sort(keys(copy(s:charset)))
...
```

It turns out const variable declaration is a new feature and was [merged in vim only in 2019](https://github.com/vim/vim/pull/4541). Users having these issues could either apply local changes to charset.vim and diacritic.vim or upgrade their vim (8.1.1539 or later) (or [neovim](https://github.com/neovim/neovim/pull/10313), version 0.4.0 or later). The local changes would be to just change const to let (this patch could have been produced by `:%s/^const /let /` in those files):

```diff
diff --git a/autoload/isotope/charset.vim b/autoload/isotope/charset.vim
index 1bfca76..89c30b3 100644
--- a/autoload/isotope/charset.vim
+++ b/autoload/isotope/charset.vim
@@ -75,2 +75,2 @@ endfun
-const s:ascii =          "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
-const s:charset = {
+let s:ascii =          "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
+let s:charset = {
@@ -105,4 +105,4 @@ const s:charset = {
-const s:keys = sort(keys(copy(s:charset)))
-const s:lo = char2nr(s:ascii[0])
-const s:hi = char2nr(s:ascii[strlen(s:ascii)-1])
-const s:undefined = ' '
+let s:keys = sort(keys(copy(s:charset)))
+let s:lo = char2nr(s:ascii[0])
+let s:hi = char2nr(s:ascii[strlen(s:ascii)-1])
+let s:undefined = ' '
diff --git a/autoload/isotope/diacritic.vim b/autoload/isotope/diacritic.vim
index a96b6f0..f7c2fa1 100644
--- a/autoload/isotope/diacritic.vim
+++ b/autoload/isotope/diacritic.vim
@@ -56 +56 @@ endfun
-const s:diacritic_raw = {
+let s:diacritic_raw = {
@@ -401,3 +401,3 @@ endfun
-const s:raw_keys = sort(copy(keys(s:diacritic_raw)))
-const s:alias_keys = sort(copy(keys(s:diacritic_alias)))
-const s:diacritic_reverse_alias = s:reverse_dict(s:diacritic_alias)
+let s:raw_keys = sort(copy(keys(s:diacritic_raw)))
+let s:alias_keys = sort(copy(keys(s:diacritic_alias)))
+let s:diacritic_reverse_alias = s:reverse_dict(s:diacritic_alias)
```

I'm not arguing for merging these changes, I hate to stand in the way of progress. Maybe just document the requirement for a recent vim and point to this issue for people unable to upgrade.

**Comment by segeljakt** [comment]
Woops, I'll merge this, thanks for the notice. 😃

**Comment by olof** [comment]
Of course that works for me as well! Thanks (and cool plugin!) :)

**Comment by segeljakt** [comment]
@olof No problem, thanks for using it 🎉
